### ISSUE TITLE
Github ci failing with core dump

### ISSUE THREAD

**Issue by alanruttenberg** [roswell/roswell#402] opened 2019-11-30 01:32 UTC
I am trying to use Roswell to run tests, as a checkin action on Github. Project: https://github.com/alanruttenberg/lilith

## Environment
```yaml

name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [abcl-bin, ccl-bin, cmu-bin, ecl]
    steps:
    - uses: actions/checkout@v1
    - name: install Lisp
      env:
        LISP: ${{matrix.LISP}}
      run: |
        export PATH=~/.roswell/bin:$PATH
        export ROSWELL_INSTALL_DIR=$HOME/.roswell
        curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
    - name: run test
      run: |
        export PATH=~/.roswell/bin:$PATH
        ros run -e '(pushnew :lilith-test *features*)'\
                -e '(load "../lilith.asd")'\
                -e '(ql:quickload :fiveam)'\
                -e '(asdf::oos (quote asdf:load-op) :lilith)'\
                -e '(push :literate-test *features*)'\
                -e '(compile-file "../lilith.org")'\
                -e '(load "../lilith.org")'\
                -e '(if (not (lilith::run-test))(uiop:quit 1))'\
                -e '(uiop:quit 0)'
```
## Expected behavior

Roswell runs the test

## Actual result

Punchline: (It never gets to run the tests) 
```log
Building sbcl-bin/1.5.9.../home/runner/.roswell/impls/x86-64/linux/sbcl-bin/1.5.9/bin/sbcl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/.roswell/impls/x86-64/linux/sbcl-bin/1.5.9/bin/sbcl)
Segmentation fault (core dumped)
```
Most of the log (downloading progress elided)

```log
2019-11-29T23:45:59.0432521Z HEAD is now at bce6054 specify sbcl version
2019-11-29T23:45:59.0446655Z Removed matchers: 'checkout-git'
2019-11-29T23:45:59.0595920Z ##[group]Run export PATH=~/.roswell/bin:$PATH
2019-11-29T23:45:59.0596251Z [36;1mexport PATH=~/.roswell/bin:$PATH[0m
2019-11-29T23:45:59.0596337Z [36;1mexport ROSWELL_INSTALL_DIR=$HOME/.roswell[0m
2019-11-29T23:45:59.0596539Z [36;1mcurl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh[0m
2019-11-29T23:45:59.0627848Z shell: /bin/bash -e {0}
2019-11-29T23:45:59.0627976Z env:
2019-11-29T23:45:59.0628069Z   LISP: abcl-bin
2019-11-29T23:45:59.0628139Z ##[endgroup]
2019-11-29T23:45:59.0745438Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-11-29T23:45:59.0750738Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-11-29T23:45:59.0751467Z 
2019-11-29T23:45:59.2659686Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2019-11-29T23:45:59.2661027Z 100  7324  100  7324    0     0  38345      0 --:--:-- --:--:-- --:--:-- 38345
2019-11-29T23:45:59.2682988Z Installing Roswell...
2019-11-29T23:45:59.2721447Z Downloading https://github.com/roswell/roswell/releases/download/v19.09.12.102/roswell_19.09.12.102-1_amd64.deb...
2019-11-29T23:45:59.2776914Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-11-29T23:45:59.2779828Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-11-29T23:45:59.2780036Z 
2019-11-29T23:45:59.4963575Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2019-11-29T23:45:59.4964269Z 100   622    0   622    0     0   3514      0 --:--:-- --:--:-- --:--:--  3514
2019-11-29T23:45:59.8245696Z 
2019-11-29T23:45:59.9494674Z  28  115k   28 33318    0     0  61246      0  0:00:01 --:--:--  0:00:01 61246
2019-11-29T23:45:59.9495173Z 100  115k  100  115k    0     0   172k      0 --:--:-- --:--:-- --:--:--  655k
2019-11-29T23:46:00.1516948Z Selecting previously unselected package roswell.
2019-11-29T23:46:07.5673650Z (Reading database ... 239995 files and directories currently installed.)
2019-11-29T23:46:07.5815197Z Preparing to unpack /tmp/roswell.deb ...
2019-11-29T23:46:07.6910929Z Unpacking roswell (19.09.12.102-1) ...
2019-11-29T23:46:08.0317135Z Setting up roswell (19.09.12.102-1) ...
2019-11-29T23:46:09.4157251Z Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
2019-11-29T23:46:11.6652953Z Roswell has been installed.
2019-11-29T23:46:11.6653655Z Installing abcl-bin...
2019-11-29T23:46:11.6768910Z Installing sbcl-bin...
2019-11-29T23:46:12.2407992Z 
2019-11-29T23:46:12.2496251Z [##########################################################################]100%
2019-11-29T23:46:12.3965838Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:12.3966471Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:12.4068465Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:12.4069072Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:12.4136722Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:12.4137428Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:12.4137998Z Downloading https://github.com/roswell/sbcl_bin/releases/download/1.5.9/sbcl-1.5.9-x86-64-linux-binary.tar.bz2
2019-11-29T23:46:12.9728193Z 
2019-11-29T23:46:13.0995035Z [                                                                          ]  0%
2019-11-29T23:46:13.1625379Z [                                                                          ]  1%
2019-11-29T23:46:13.1630542Z [#                                                                         ]  1%
2019-11-29T23:46:13.2258050Z [#                                                                         ]  2%

2019-11-29T23:46:13.6070107Z [######################################################################### ] 99%
2019-11-29T23:46:13.6165282Z [##########################################################################]100%
2019-11-29T23:46:13.6261139Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:13.6261595Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:13.6262091Z Downloading https://github.com/roswell/sbcl_bin/releases/download/1.5.9/sbcl-1.5.9-x86-64-linux-binary.tar.bz2
2019-11-29T23:46:13.6262544Z Extracting sbcl-bin-1.5.9-x86-64-linux.tar.bz2 to /home/runner/.roswell/src/sbcl-1.5.9-x86-64-linux/
2019-11-29T23:46:15.0132102Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:15.0132651Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:15.0133175Z Downloading https://github.com/roswell/sbcl_bin/releases/download/1.5.9/sbcl-1.5.9-x86-64-linux-binary.tar.bz2
2019-11-29T23:46:15.0133672Z Extracting sbcl-bin-1.5.9-x86-64-linux.tar.bz2 to /home/runner/.roswell/src/sbcl-1.5.9-x86-64-linux/
2019-11-29T23:46:15.0186377Z No SBCL version specified. Downloading platform-table.html to see the available versions...
2019-11-29T23:46:15.0186920Z Installing sbcl-bin/1.5.9...
2019-11-29T23:46:15.0187438Z Downloading https://github.com/roswell/sbcl_bin/releases/download/1.5.9/sbcl-1.5.9-x86-64-linux-binary.tar.bz2
2019-11-29T23:46:15.0188097Z Extracting sbcl-bin-1.5.9-x86-64-linux.tar.bz2 to /home/runner/.roswell/src/sbcl-1.5.9-x86-64-linux/
2019-11-29T23:46:15.2103142Z Building sbcl-bin/1.5.9.../home/runner/.roswell/impls/x86-64/linux/sbcl-bin/1.5.9/bin/sbcl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/runner/.roswell/impls/x86-64/linux/sbcl-bin/1.5.9/bin/sbcl)
2019-11-29T23:46:15.6659124Z Segmentation fault (core dumped)
2019-11-29T23:46:15.6670110Z ##[error]Process completed with exit code 139.
2019-11-29T23:46:15.6692621Z Cleaning up orphan processes
```

**Comment by neil-lindquist** [comment] 2019-12-01 01:37
I'm seeing similar behavior on Travis (https://travis-ci.org/neil-lindquist/CI-Utils/builds/619097800), Bitbucket Pipelines (https://bitbucket.org/nlindqu1/ci-utils/addon/pipelines/home#!/results/26), and Circle CI (https://circleci.com/gh/neil-lindquist/CI-Utils/138).
Appveyor, Gitlab CI, and Azure Pipelines all seem unaffected

**Comment by guicho271828** [comment] 2019-12-03 17:15
Hi all, I am writing on behalf of @snmsts as he has a problem with his 2fa and cannot log in to github right now.

We identified the problem is that the wrong binary -- technically, the same binary from the SBCL website which recently started to be linked specifically to require GLIBC 2.28 -- was uploaded to [roswell/sbcl_bin](https://github.com/roswell/sbcl_bin) repo instead of the binary it built by its own on Travis. The issue is fixed now, plz rerun your build and see. In my project it started working.

**Closed by guicho271828** 2019-12-03 17:15 UTC

**Comment by neil-lindquist** [comment] 2019-12-03 20:47
Yep, that fixed it.  Thank you.
